---
# tasks file for deploy_nginx
    - name: Pull image Nginx
      docker_image:
        name: nginx:latest
        source: pull

   
    - name: Create Docker Nginx
      docker_container:
        name: nginx
        image: nginx:latest
        networks:
          - name: "{{ network_nginx }}"        
        ports:
          - "{{ nginx_port }}:{{ nginx_port }}"
        memory: "{{ nginx_memory }}"
        restart_policy: always
        state: started
