
# tasks file for install_docker
---
- block:
    - name: Install prerequisites
      apt:
        state: present
        name:
          - apt-transport-https
          - ca-certificates 
          - curl 
          - gnupg-agent
          - software-properties-common
        update_cache: yes

    - name: Add apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Install docker 
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes

    - name: Install python package manager
      apt:
        name: python3-pip
  
    - name: Install python sdk
      pip:
        name:
          - docker
          - docker-compose
  when: ansible_os_family == "Debian"

- block:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
 
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
 
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
 
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
 
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
    - name: Install python package manager
      yum:
        name: python3-pip

    - name: Install python sdk
      pip:
        name:
          - docker
          - docker-compose

 
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes 

  when: ansible_os_family == "RedHat"
